jest.mock("src/envService", () => ({
  getFirebaseAPIKey: jest.fn(() => "mock-api-key"),
  getFirebaseDomain: jest.fn(() => "mock-auth-domain"),
  getBackendUrl: jest.fn(() => "mock-backend-url"),
  getApplicationLoginCode: jest.fn(() => ""),
  getApplicationRegistrationCode: jest.fn(() => ""),
  getLoginCodeDisabled: jest.fn(() => "false"),
  getRegistrationDisabled: jest.fn(() => "false"),
  getMetricsEnabled: jest.fn(() => "true"),
  getMetricsConfig: jest.fn(() => ""),
  getFeatures: jest.fn(() => ""),
  getCvUploadEnabled: jest.fn(() => "true"),
  getNewSessionEnabled: jest.fn(() => false),
  getSocialAuthDisabled: jest.fn(() => "false"),
  getSupportedLocales: jest.fn(() => JSON.stringify(["en-US"])),
  getDefaultLocale: jest.fn(() => "en-US"),
  getProductName: jest.fn(() => "mockProduct"),
  getCountryName: jest.fn(() => "your country"),
  getBrowserTabTitle: jest.fn(() => "Mocked Browser Tab Title"),
  getMetaDescription: jest.fn(() => "Mocked Meta Description"),
  getSeoEnvVar: jest.fn(() => "{}"),
  getSkillsReportOutputConfigEnvVar: jest.fn(() => "{}"),
  ensureRequiredEnvVars: jest.fn(() => {}),
  getLogoUrl: jest.fn(() => "mock-logo-url"),
  getPartnerLogos: jest.fn(() => []),
  getDarkLogoUrl: jest.fn(() => ""),
  getFaviconUrl: jest.fn(() => "mock-favicon-url"),
  getAppIconUrl: jest.fn(() => "mock-app-icon-url"),
  getThemeCssVariables: jest.fn(() => "{}"),
  getRegistrationCodeDisabled: jest.fn(() => "false"),
  getGtmContainerId: jest.fn(() => ""),
  getGtmEnabled: jest.fn(() => "false"),
  getChatAvatarUrl: jest.fn(() => ""),
  getFaqTutorialVideoUrl: jest.fn(() => ""),
  getProgramSkillsVisibility: jest.fn(() => true),
  getIllustrationUrls: jest.fn(() => ({
    loginHero: { src: "/climber.svg" },
    loginFeature1: { src: "/conversation.svg" },
    loginFeature2: { src: "/resume.svg" },
    loginFeature3: { src: "/runner.svg" },
    homeHero: { src: "/path.svg" },
    careerReadinessHero: { src: "/thinkers.svg" },
    authShapesBackground: { src: "/Shapes.svg" },
  })),
}));
