net:
  port: 27017
  bindIpAll: true
replication:
  replSetName: rs0
setParameter:
  # mongod hands search index management and $search/$vectorSearch queries to mongot
  searchIndexManagementHostAndPort: mongot:27028
  mongotHost: mongot:27028
  skipAuthenticationToSearchIndexManagementServer: false
  useGrpcForSearch: true
  searchTLSMode: disabled
